### PR TITLE
added proxy support through passing proxy property in options

### PR DESCRIPTION
**Pull request by bmarks-mylo**
I didn't want to add a check for an environment variable in the session module since this is cross node/browser so I added a proxy property to options instead.

Your contribution guidelines state that there are phantom tests but I don't see them in any branch.  All jasmine tests work with/without an http_proxy env set when appropriate.

### CODE REVIEW

**Comment by KevinGlinski** [comment]
can you add a note about this in the readme?

**Comment by bmarks-mylo** [comment]
added a proxy blurb to the readme

**Comment by bmarks-mylo** [comment]
What does your release process look like?  Any idea when this would be released to NPM or tagged as a GitHub release?

**Comment by KevinGlinski** [comment]
I just pushed a release to npm

**Comment by bmarks-mylo** [comment]
I don't see any of the changes in my PR in the latest 0.72.5 or 0.72.6.  Were my changes squashed?

**Comment by bmarks-mylo** [comment]
Looks like #d60e05e squashed my changes.

**Comment by KevinGlinski** [comment]
i screwed up the review, dist/partials/purecloudsession.js is a generated file, you need to make the changes in templates/purecloudsession.js

**Pull request merged**
