### PR TITLE
updated purecloud session to support proxy

### PR DESCRIPTION
**Pull request by bmarks-mylo**
Let me know if you want the post-gulp dist files or just the change to the templates/purecloudsession.js

### CODE REVIEW

**Comment by KevinGlinski** [comment]
just this file is fine

**Comment by bmarks-mylo** [comment]
Can I get another release today/tomorrow?

**Comment by KevinGlinski** [comment]
released, also fixed the npm publish so there should be a npm release for each release in github going forward.

**Comment by KevinGlinski** [comment]
Reverting this PR.  looks like superagent-proxy is not compatible with browserify.  When the sdk is used in the browser there is an error ```semver.js:293 Uncaught TypeError: Invalid Version: ```

looks like the root of the issue is line 70312 where it checks process.version

~~~
// we only need to patch the `http.request()` and
// `http.ClientRequest` on older versions of Node.js
if (semver.lt(process.version, '0.11.8')) {
  // subclass the native ClientRequest to include the
  // passed in `options` object.
~~~

**Comment by bmarks-mylo** [comment]
It looks like this is the offending repo and someone has already raised this issue:

https://github.com/TooTallNate/node-agent-base/issues/4

I'll see if I can make headway on this issue an then hopefully roll that fix back up through here.

**Pull request merged**
